### PR TITLE
Bump min s2geography version to 0.2.0

### PR DESCRIPTION
**Pull request by benbovy**
@jorisvandenbossche do you see any good reason to maintain compatibility with s2geography <0.2.0?

If not, I can remove the special cases (`#if` / `#endif` pre-processor blocks) for s2geography < 0.2.0 and I can move forward here with some refactoring of core functionality (e.g., clone s2geography objects) that would otherwise be cumbersome to make if we want to maintain compatibility with older s2geography versions.

### CODE REVIEW

**Comment by martinfleis** [comment]
Given spherely does not have any release compatible with 0.1.0 I don't see a reason to promise any backwards compatibility at this point.

**Comment by benbovy** [comment]
Yes I agree. I also think it will be unlikely to have s2geography as a common dependency of multiple downstream packages in the same environment so maintaining backwards compatibility probably won't be very useful anyway except for development iterations, keeping CI running, etc. between the releases.

**Comment by jorisvandenbossche** [comment]
Yep, fully agreed just bumping the minimum version, and cleaning up the code. 
Maybe you can just keep the machinery in cmakelists.txt to provide the version to be able to have those `#if` / `#endif` pre-processor blocks (we might use those in the near future again for temporary using things from s2geography 0.3dev until we do a new release)

**Comment by jorisvandenbossche** [comment]
You can also remove some skips in the tests, eg 

https://github.com/benbovy/spherely/blob/d40a8d25fe6d18bd65d713cf9d5c658668c1a728/tests/test_io.py#L10-L13

**Comment by benbovy** [comment]
This PR is ready for review. I'll implement new spherely features on top of s2geography 0.2.0 in follow-up PRs.

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
